FROM tddpirate/androidstudio:1.4
MAINTAINER Omer Zak "w1@zak.co.il"
RUN sudo npm install -g cordova

USER developer
# ENV HOME=/AndroidStudio/home DISPLAY=:0 SHELL=/bin/bash
# ENV ANDROID_HOME=$HOME/Android/Sdk
# ENV PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

ENTRYPOINT /bin/bash